events {}

http {
  upstream jewelry_api {
    server api-1:3000;
    server api-2:3000;
    server api-3:3000;

    keepalive 32;
  }

  server {
    listen 80;
    server_name _;

    location = /nginx-health {
      access_log off;
      add_header Content-Type text/plain;
      return 200 "ok\n";
    }

    location / {
      proxy_pass http://jewelry_api;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
