ALTER TABLE "Shop" ADD COLUMN "currencyCode" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "Shop" ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'en-US';

ALTER TABLE "Sale" ADD COLUMN "currencyCode" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "Invoice" ADD COLUMN "currencyCode" TEXT NOT NULL DEFAULT 'USD';
